### ISSUE TITLE
unable to download lightcurves

### ISSUE THREAD

**Issue by pilchat** [afeinstein20/stella#11]
Hi,

I am using stella 0.1.0 installed via pip. I am trying to download the lightcurves with:

>download.download_lightcurves()

but it is extremely slow: it created ~70 .npy files after 3 hours though my internet connection is superfast. After that, it gave me this error:

>File "python3.7/site-packages/astroquery/mast/core.py", line 607, in _parse_result
>    raise RemoteServiceError(result.get('msg', "There was an error with your request."))

>RemoteServiceError: Cannot continue the execution because the session is in the kill state.

is it ok that the process is this slow and eventually gets killed by the server?

thanks

**Comment by afeinstein20** [comment]
Thanks for pinging me about this again! I'm not sure how much help I can be with this issue, since it seems to be on the MAST server side. I've had trouble in the past downloading a lot of light curves at once, but usually if I try again a few hours or another day, it works just fine.

Alternatively, if you're not hoping to retrain all of the CNN models from scratch, I just wrote a new function to download the models, which are now hosted on MAST. This downloads as a `.tar.gz` file, so is much faster! You can get the models through `stella` by calling: `ds = stella.DownloadSets.download_models()` 

This will set the attributes 

- `ds.model_dir` = where the files were downloaded
- `ds.models` = the path + filenames of the models

By default, `ds.models` will be the 10 models used in the analysis of our paper. If you want access to all 100 models, you can simply set `ds = stella.DownloadSets.download_models(all_models=True)`. I will work on incorporating this into the docs over the next few days, but let me know if you have any questions until then!

**Comment by pilchat** [comment]
hi,

I think I will wait for the update of the docs: can you notify me when you
will be done?

Moreover, what should I do to get the new functionality? I tried pip
upgrade but no newer version of stella has been installed. Maybe I have to
clone the git repo?

thanks a lot

**Comment by afeinstein20** [comment]
I can definitely notify you when that's up. And yes, you have to clone the git repo to get that function right now!

**Comment by pilchat** [comment]
Hi Adina,

any updates?

thanks

**Comment by afeinstein20** [comment]
I believe the docs have been properly updated now! Sorry for such a delay. Let me know if you are still having issues.
